name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  OCTOKIT_GITHUB_API_BASE_URL:
    description: "GitHub API base URL."
    required: false
    default: "https://api.github.com"
  ADDITIONAL_PROMPT_CRITERIA:
    description: "additional lines that should be included in the OpenAI prompt"
    required: false
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
